# Site settings
title: Alles Blogg
email: an223dn@student.lnu.se
description: > # Denna sidan är till för att presentera mig och mina arbeten.:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "A11333.github.io" #
twitter_username: NilssonAlle
github_username:  A11333

# Build settings
markdown: kramdown
